//! PROTOTYPE (not yet runnable): reconstruct a group signature from a mix of
//! Pluto- and Charon-generated key shares.
//!
//! This file is a forward specification, not a working test. It is `#[ignore]`d
//! so it never runs in CI; it pins the target and the missing fixture.
//!
//! ## Why this matters
//!
//! Charon compatibility must hold at the *cryptographic* layer, not just for
//! JSON parsing. After a mixed DKG ceremony (some operators on Charon, some on
//! Pluto), every node holds a private share of the **same** distributed
//! validator key. The cluster is only interoperable if a threshold of those
//! shares — regardless of which implementation produced each one — reconstructs
//! a group signature that verifies against the DV public key.
//!
//! ## What already exists
//!
//! - Pure-Pluto t-of-n reconstruction is tested: partials from a threshold of
//!   Pluto shares aggregate to a valid group signature
//!   (`crates/dkg/src/frostp2p_integ_test.rs:502-536`, via
//!   `BlstImpl::threshold_aggregate` + `BlstImpl::verify`).
//! - A mixed 2 Charon + 2 Pluto DKG ceremony runs in CI
//!   (`.github/workflows/dkg-runner.yml`). But its semantic check only asserts
//!   the lock's `signature_aggregate` has the right byte length
//!   (`scripts/dkg-runner/ci/verify-output-semantic.sh`), not that a fresh
//!   threshold reconstruction from the mixed shares verifies cryptographically.
//!
//! ## What is missing (the gap)
//!
//! Committed test fixtures containing the **private** key shares produced by
//! Charon for a known group key. The reconstruction primitive
//! (`BlstImpl::threshold_aggregate`) exists and works for Pluto shares; what is
//! absent is access to Charon-generated shares inside a Rust test. A real test
//! needs either captured per-node keystores from a mixed `dkg-runner` ceremony
//! (group pubkey + at least a threshold of secret shares, some authored by
//! Charon) or a committed interop fixture. Running Charon itself from a unit
//! test is out of scope.
//!
//! ## Target scenario (to assert once fixtures exist)
//!
//! 1. Load a known distributed-validator group public key and a threshold of
//!    private shares, where at least one share was generated by Charon and at
//!    least one by Pluto.
//! 2. Sign a fixed message with each share to produce partial signatures.
//! 3. `BlstImpl::threshold_aggregate` the partials and assert the result
//!    verifies against the group public key — proving Charon and Pluto shares
//!    are cryptographically interchangeable, not merely format-compatible.

/// Forward spec for reconstructing a group signature from mixed Charon/Pluto
/// shares. Ignored and intentionally unimplemented: it needs committed Charon
/// private-share fixtures (see the module docs above).
#[test]
#[ignore = "blocked: no committed Charon-generated private share fixtures to reconstruct from"]
fn prototype_test_reconstruct_group_signature_from_mixed_pluto_charon_shares() {
    unimplemented!(
        "specification only — implement once a mixed-ceremony fixture provides Charon-generated \
         private shares for a known group key (see module docs)"
    );
}
