//! Benchmarks for protobuf (de)serialization of consensus wire messages.
//!
//! Benchmark ids follow the cross-language pair naming used by
//! `perf/pairs.json`; the Go counterparts live in `perf/go-bench/`. The
//! fixture is a round-3 QBFTConsensusMsg with four justifications and a 1KiB
//! value, generated by the Go side.
#![allow(missing_docs)]

use std::{hint::black_box, time::Duration};

use criterion::{Criterion, criterion_group, criterion_main};
use pluto_core::corepb::v1::consensus::QbftConsensusMsg;
use prost::Message;

const QBFT_MSG_PB: &[u8] = include_bytes!("../../../perf/fixtures/qbft_consensus_msg.pb");

fn bench_qbft_msg(c: &mut Criterion) {
    let msg = QbftConsensusMsg::decode(QBFT_MSG_PB).expect("bench setup: decode fixture");
    assert_eq!(
        msg.encode_to_vec(),
        QBFT_MSG_PB,
        "qbft msg fixture round-trip mismatch"
    );

    c.bench_function("tier1/proto/qbft_marshal", |b| {
        b.iter(|| black_box(&msg).encode_to_vec())
    });

    c.bench_function("tier1/proto/qbft_unmarshal", |b| {
        b.iter(|| QbftConsensusMsg::decode(black_box(QBFT_MSG_PB)).expect("decode should succeed"))
    });
}

fn config() -> Criterion {
    Criterion::default()
        .sample_size(50)
        .measurement_time(Duration::from_secs(3))
}

criterion_group! {
    name = benches;
    config = config();
    targets = bench_qbft_msg,
}
criterion_main!(benches);
