//!
//! AUTO-GENERATED CODE - DO NOT EDIT!
//!
//! Eth Beacon Node API
//! Source: build/beacon-node-oapi.json
//! Version: v4.0.0 - Ethereum Proof-of-Stake Consensus Specification v1.5.0
//! Generated by `oas3-gen v0.24.0`
//!
//! API specification for the beacon node, which enables users to query and participate in Ethereum 2.0 phase 0 beacon chain.
//! 
//! All requests by default send and receive JSON, and as such should have either or both of the "Content-Type: application/json"
//! and "Accept: application/json" headers.  In addition, some requests can send and receive data in the SSZ format.  The header
//! "Content-Type: application/octet-stream" should be set in requests that contain SSZ data; a preference to receive SSZ data in
//! response can be indicated by setting the "Accept: application/octet-stream;q=1.0,application/json;q=0.9" header.  Note that
//! only a subset of requests can respond with data in SSZ format; these are noted in each individual request.
//! 
//! When handling requests, the server should return a 415 status code if the "Content-Type" header in the request specifies a format
//! that is not supported.  Similarly, it should return a 406 status code if it cannot produce a response in the format accepted by
//! the client as specified in the "Accept" header; if no "Accept" header is provided then it is assumed to be "application/json".
//! In any case, the server should indicate the format of the response by setting the corresponding "Content-Type" header.
//! 
//! API endpoints are individually versioned.  As such, there is no direct relationship between all v1 endpoints, all v2 endpoints,
//! _etc._ and no such relationship should be inferred.  All JSON responses return the requested data under a `data` key in the top
//! level of their response.  Additional metadata may or may not be present in other keys at the top level of the response, dependent
//! on the endpoint.  The rules that require an increase in version number are as follows:
//! 
//!   - no field that is listed in an endpoint shall be removed without an increase in the version number
//!   - no field that is listed in an endpoint shall be altered in terms of format (_e.g._ from a string to an array) without an
//!     increase in the version number
//! 
//! Note that it is possible for a field to be added to an endpoint's data or metadata without an increase in the version number.
//! 

use anyhow::Context;
use reqwest::{Client, Url};
use validator::Validate;
use super::types::*;
pub const BASE_URL: &str = "{server_url}";
#[derive(Debug, Clone)]
pub struct EthBeaconNodeApiClient {
    pub client: Client,
    pub base_url: Url,
}
impl Default for EthBeaconNodeApiClient {
    fn default() -> Self {
        Self::new()
    }
}
impl EthBeaconNodeApiClient {
    /// Create a client using the OpenAPI `servers[0]` URL.
    #[must_use]
    #[track_caller]
    pub fn new() -> Self {
        Self {
            client: Client::builder().build().expect("client"),
            base_url: Url::parse(BASE_URL).expect("valid base url"),
        }
    }
    /// Create a client with a custom base URL.
    pub fn with_base_url(base_url: impl AsRef<str>) -> anyhow::Result<Self> {
        Ok(Self {
            client: Client::builder().build().context("building reqwest client")?,
            base_url: Url::parse(base_url.as_ref()).context("parsing base url")?,
        })
    }
    /// Create a client from an existing `reqwest::Client`.
    pub fn with_client(
        base_url: impl AsRef<str>,
        client: Client,
    ) -> anyhow::Result<Self> {
        let url = Url::parse(base_url.as_ref()).context("parsing base url")?;
        Ok(Self { client, base_url: url })
    }
    ///Get blinded block
    ///
    ///Retrieves blinded block for given block ID.
    ///Depending on `Accept` header it can be returned either as JSON or as bytes serialized by SSZ
    ///
    ///GET /eth/v1/beacon/blinded_blocks/{block_id}
    pub async fn get_blinded_block(
        &self,
        request: GetBlindedBlockRequest,
    ) -> anyhow::Result<GetBlindedBlockResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("beacon")
            .push("blinded_blocks")
            .push(&request.path.block_id.to_string());
        let response = self.client.get(url).send().await?;
        Ok(GetBlindedBlockRequest::parse_response(response).await?)
    }
    ///Get blob sidecars
    ///
    ///Retrieves blob sidecars for a given block id.
    ///Depending on `Accept` header it can be returned either as json or as bytes serialized by SSZ.
    ///
    ///If the `indices` parameter is specified, only the blob sidecars with the specified indices will be returned. There are no guarantees
    ///for the returned blob sidecars in terms of ordering.
    ///
    ///GET /eth/v1/beacon/blob_sidecars/{block_id}
    pub async fn get_blob_sidecars(
        &self,
        request: GetBlobSidecarsRequest,
    ) -> anyhow::Result<GetBlobSidecarsResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("beacon")
            .push("blob_sidecars")
            .push(&request.path.block_id.to_string());
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(GetBlobSidecarsRequest::parse_response(response).await?)
    }
    ///Get blobs
    ///
    ///Retrieves blobs for a given block id.
    ///Depending on `Accept` header it can be returned either as json or as bytes serialized by SSZ.
    ///
    ///If the `versioned_hashes` parameter is specified, only the blobs for the specified versioned hashes will be returned. Blobs are
    ///returned as an ordered list matching the order of their corresponding KZG commitments in the block.
    ///
    ///After the Fulu fork, only supernodes (which custody all data columns) are required to return blobs. Clients may implement
    ///blob reconstruction logic for non-super nodes.
    ///
    ///GET /eth/v1/beacon/blobs/{block_id}
    pub async fn get_blobs(
        &self,
        request: GetBlobsRequest,
    ) -> anyhow::Result<GetBlobsResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("beacon")
            .push("blobs")
            .push(&request.path.block_id.to_string());
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(GetBlobsRequest::parse_response(response).await?)
    }
    ///Get block root
    ///
    ///Retrieves hashTreeRoot of BeaconBlock/BeaconBlockHeader
    ///
    ///GET /eth/v1/beacon/blocks/{block_id}/root
    pub async fn get_block_root(
        &self,
        request: GetBlockRootRequest,
    ) -> anyhow::Result<GetBlockRootResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("beacon")
            .push("blocks")
            .push(&request.path.block_id.to_string())
            .push("root");
        let response = self.client.get(url).send().await?;
        Ok(GetBlockRootRequest::parse_response(response).await?)
    }
    ///Retrieve details of the chain's genesis.
    ///
    ///Retrieve details of the chain's genesis which can be used to identify chain.
    ///
    ///GET /eth/v1/beacon/genesis
    pub async fn get_genesis(
        &self,
        request: GetGenesisRequest,
    ) -> anyhow::Result<GetGenesisResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("beacon")
            .push("genesis");
        let response = self.client.get(url).send().await?;
        Ok(GetGenesisRequest::parse_response(response).await?)
    }
    ///Get block headers
    ///
    ///Retrieves block headers matching given query. By default it will fetch current head slot blocks.
    ///
    ///GET /eth/v1/beacon/headers
    pub async fn get_block_headers(
        &self,
        request: GetBlockHeadersRequest,
    ) -> anyhow::Result<GetBlockHeadersResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("beacon")
            .push("headers");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(GetBlockHeadersRequest::parse_response(response).await?)
    }
    ///Get block header
    ///
    ///Retrieves block header for given block id.
    ///
    ///GET /eth/v1/beacon/headers/{block_id}
    pub async fn get_block_header(
        &self,
        request: GetBlockHeaderRequest,
    ) -> anyhow::Result<GetBlockHeaderResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("beacon")
            .push("headers")
            .push(&request.path.block_id.to_string());
        let response = self.client.get(url).send().await?;
        Ok(GetBlockHeaderRequest::parse_response(response).await?)
    }
    ///Get `LightClientBootstrap` structure for a requested block root
    ///
    ///Requests the [`LightClientBootstrap`](https://github.com/ethereum/consensus-specs/blob/v1.3.0/specs/altair/light-client/sync-protocol.md#lightclientbootstrap) structure corresponding to a given post-Altair beacon block root.
    ///Depending on the `Accept` header it can be returned either as JSON or SSZ-serialized bytes.
    ///
    ///Servers SHOULD provide results as defined in [`create_light_client_bootstrap`](https://github.com/ethereum/consensus-specs/blob/v1.3.0/specs/altair/light-client/full-node.md#create_light_client_bootstrap). To fulfill a request, the requested block's post state needs to be known.
    ///
    ///GET /eth/v1/beacon/light_client/bootstrap/{block_root}
    pub async fn get_light_client_bootstrap(
        &self,
        request: GetLightClientBootstrapRequest,
    ) -> anyhow::Result<GetLightClientBootstrapResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("beacon")
            .push("light_client")
            .push("bootstrap")
            .push(&request.path.block_root.to_string());
        let response = self.client.get(url).send().await?;
        Ok(GetLightClientBootstrapRequest::parse_response(response).await?)
    }
    ///Get the latest known `LightClientFinalityUpdate`
    ///
    ///Requests the latest [`LightClientFinalityUpdate`](https://github.com/ethereum/consensus-specs/blob/v1.3.0/specs/altair/light-client/sync-protocol.md#lightclientfinalityupdate) known by the server.
    ///Depending on the `Accept` header it can be returned either as JSON or SSZ-serialized bytes.
    ///
    ///Servers SHOULD provide results as defined in [`create_light_client_finality_update`](https://github.com/ethereum/consensus-specs/blob/v1.3.0/specs/altair/light-client/full-node.md#create_light_client_finality_update).
    ///
    ///GET /eth/v1/beacon/light_client/finality_update
    pub async fn get_light_client_finality_update(
        &self,
        request: GetLightClientFinalityUpdateRequest,
    ) -> anyhow::Result<GetLightClientFinalityUpdateResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("beacon")
            .push("light_client")
            .push("finality_update");
        let response = self.client.get(url).send().await?;
        Ok(GetLightClientFinalityUpdateRequest::parse_response(response).await?)
    }
    ///Get the latest known `LightClientOptimisticUpdate`
    ///
    ///Requests the latest [`LightClientOptimisticUpdate`](https://github.com/ethereum/consensus-specs/blob/v1.3.0/specs/altair/light-client/sync-protocol.md#lightclientoptimisticupdate) known by the server.
    ///Depending on the `Accept` header it can be returned either as JSON or SSZ-serialized bytes.
    ///
    ///Servers SHOULD provide results as defined in [`create_light_client_optimistic_update`](https://github.com/ethereum/consensus-specs/blob/v1.3.0/specs/altair/light-client/full-node.md#create_light_client_optimistic_update).
    ///
    ///GET /eth/v1/beacon/light_client/optimistic_update
    pub async fn get_light_client_optimistic_update(
        &self,
        request: GetLightClientOptimisticUpdateRequest,
    ) -> anyhow::Result<GetLightClientOptimisticUpdateResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("beacon")
            .push("light_client")
            .push("optimistic_update");
        let response = self.client.get(url).send().await?;
        Ok(GetLightClientOptimisticUpdateRequest::parse_response(response).await?)
    }
    ///Get `LightClientUpdate` instances in a requested sync committee period range
    ///
    ///Requests the [`LightClientUpdate`](https://github.com/ethereum/consensus-specs/blob/v1.3.0/specs/altair/light-client/sync-protocol.md#lightclientupdate) instances in the sync committee period range `[start_period, start_period + count)`, leading up to the current head sync committee period as selected by fork choice.
    ///Depending on the `Accept` header they can be returned either as JSON or SSZ-serialized bytes.
    ///
    ///Servers SHOULD provide results as defined in [`create_light_client_update`](https://github.com/ethereum/consensus-specs/blob/v1.3.0/specs/altair/light-client/full-node.md#create_light_client_update). They MUST respond with at least the earliest known result within the requested range, and MUST send results in consecutive order (by period). The response MUST NOT contain more than [`min(MAX_REQUEST_LIGHT_CLIENT_UPDATES, count)`](https://github.com/ethereum/consensus-specs/blob/v1.3.0/specs/altair/light-client/p2p-interface.md#configuration) results.
    ///
    ///GET /eth/v1/beacon/light_client/updates
    pub async fn get_light_client_updates_by_range(
        &self,
        request: GetLightClientUpdatesByRangeRequest,
    ) -> anyhow::Result<GetLightClientUpdatesByRangeResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("beacon")
            .push("light_client")
            .push("updates");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(GetLightClientUpdatesByRangeRequest::parse_response(response).await?)
    }
    ///Get SignedBLSToExecutionChange from operations pool
    ///
    ///Retrieves BLS to execution changes known by the node but not necessarily incorporated into any block
    ///
    ///GET /eth/v1/beacon/pool/bls_to_execution_changes
    pub async fn get_pool_blsto_execution_changes(
        &self,
        request: GetPoolBlstoExecutionChangesRequest,
    ) -> anyhow::Result<GetPoolBlstoExecutionChangesResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("beacon")
            .push("pool")
            .push("bls_to_execution_changes");
        let response = self.client.get(url).send().await?;
        Ok(GetPoolBlstoExecutionChangesRequest::parse_response(response).await?)
    }
    ///Submit SignedBLSToExecutionChange object to node's pool
    ///
    ///Submits a list of SignedBLSToExecutionChange objects to node's pool. Any that pass validation MUST be broadcast to the network.
    ///
    ///POST /eth/v1/beacon/pool/bls_to_execution_changes
    pub async fn submit_pool_blsto_execution_change(
        &self,
        request: SubmitPoolBlstoExecutionChangeRequest,
    ) -> anyhow::Result<PublishContributionAndProofsResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("beacon")
            .push("pool")
            .push("bls_to_execution_changes");
        let response = self.client.post(url).json(&request.body).send().await?;
        Ok(SubmitPoolBlstoExecutionChangeRequest::parse_response(response).await?)
    }
    ///Get ProposerSlashings from operations pool
    ///
    ///Retrieves proposer slashings known by the node but not necessarily incorporated into any block
    ///
    ///GET /eth/v1/beacon/pool/proposer_slashings
    pub async fn get_pool_proposer_slashings(
        &self,
        request: GetPoolProposerSlashingsRequest,
    ) -> anyhow::Result<GetPoolProposerSlashingsResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("beacon")
            .push("pool")
            .push("proposer_slashings");
        let response = self.client.get(url).send().await?;
        Ok(GetPoolProposerSlashingsRequest::parse_response(response).await?)
    }
    ///Submit ProposerSlashing object to node's pool
    ///
    ///Submits ProposerSlashing object to node's pool and if passes validation  node MUST broadcast it to network.
    ///
    ///POST /eth/v1/beacon/pool/proposer_slashings
    pub async fn submit_pool_proposer_slashings(
        &self,
        request: SubmitPoolProposerSlashingsRequest,
    ) -> anyhow::Result<SubmitPoolVoluntaryExitResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("beacon")
            .push("pool")
            .push("proposer_slashings");
        let response = self.client.post(url).json(&request.body).send().await?;
        Ok(SubmitPoolProposerSlashingsRequest::parse_response(response).await?)
    }
    ///Submit sync committee signatures to node
    ///
    ///Submits sync committee signature objects to the node.
    ///
    ///Sync committee signatures are not present in phase0, but are required for Altair networks.
    ///
    ///If a sync committee signature is validated successfully the node MUST publish that sync committee signature on all applicable subnets.
    ///
    ///If one or more sync committee signatures fail validation the node MUST return a 400 error with details of which sync committee signatures have failed, and why.
    ///
    ///POST /eth/v1/beacon/pool/sync_committees
    pub async fn submit_pool_sync_committee_signatures(
        &self,
        request: SubmitPoolSyncCommitteeSignaturesRequest,
    ) -> anyhow::Result<PublishContributionAndProofsResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("beacon")
            .push("pool")
            .push("sync_committees");
        let response = self.client.post(url).json(&request.body).send().await?;
        Ok(SubmitPoolSyncCommitteeSignaturesRequest::parse_response(response).await?)
    }
    ///Get SignedVoluntaryExit from operations pool
    ///
    ///Retrieves voluntary exits known by the node but not necessarily incorporated into any block
    ///
    ///GET /eth/v1/beacon/pool/voluntary_exits
    pub async fn get_pool_voluntary_exits(
        &self,
        request: GetPoolVoluntaryExitsRequest,
    ) -> anyhow::Result<GetPoolVoluntaryExitsResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("beacon")
            .push("pool")
            .push("voluntary_exits");
        let response = self.client.get(url).send().await?;
        Ok(GetPoolVoluntaryExitsRequest::parse_response(response).await?)
    }
    ///Submit SignedVoluntaryExit object to node's pool
    ///
    ///Submits SignedVoluntaryExit object to node's pool and if passes validation node MUST broadcast it to network.
    ///
    ///POST /eth/v1/beacon/pool/voluntary_exits
    pub async fn submit_pool_voluntary_exit(
        &self,
        request: SubmitPoolVoluntaryExitRequest,
    ) -> anyhow::Result<SubmitPoolVoluntaryExitResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("beacon")
            .push("pool")
            .push("voluntary_exits");
        let response = self.client.post(url).json(&request.body).send().await?;
        Ok(SubmitPoolVoluntaryExitRequest::parse_response(response).await?)
    }
    ///Get attestations rewards
    ///
    ///Retrieve attestation reward info for validators specified by array of public keys or validator index. If no array is provided, return reward info for every validator.
    ///
    ///POST /eth/v1/beacon/rewards/attestations/{epoch}
    pub async fn get_attestations_rewards(
        &self,
        request: GetAttestationsRewardsRequest,
    ) -> anyhow::Result<GetAttestationsRewardsResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("beacon")
            .push("rewards")
            .push("attestations")
            .push(&request.path.epoch.to_string());
        let mut req_builder = self.client.post(url);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(GetAttestationsRewardsRequest::parse_response(response).await?)
    }
    ///Get block rewards
    ///
    ///Retrieve block reward info for a single block. The rewards value is the sum
    ///of values of the proposer rewards from attestations, sync committees and
    ///slashings included in the proposal.
    ///
    ///GET /eth/v1/beacon/rewards/blocks/{block_id}
    pub async fn get_block_rewards(
        &self,
        request: GetBlockRewardsRequest,
    ) -> anyhow::Result<GetBlockRewardsResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("beacon")
            .push("rewards")
            .push("blocks")
            .push(&request.path.block_id.to_string());
        let response = self.client.get(url).send().await?;
        Ok(GetBlockRewardsRequest::parse_response(response).await?)
    }
    ///Get sync committee rewards
    ///
    ///Retrieves rewards info for sync committee members specified by array of public keys or validator index. If no array is provided, return reward info for every committee member.
    ///
    ///POST /eth/v1/beacon/rewards/sync_committee/{block_id}
    pub async fn get_sync_committee_rewards(
        &self,
        request: GetSyncCommitteeRewardsRequest,
    ) -> anyhow::Result<GetSyncCommitteeRewardsResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("beacon")
            .push("rewards")
            .push("sync_committee")
            .push(&request.path.block_id.to_string());
        let mut req_builder = self.client.post(url);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(GetSyncCommitteeRewardsRequest::parse_response(response).await?)
    }
    ///Get all committees for a state.
    ///
    ///Retrieves the committees for the given state.
    ///
    ///GET /eth/v1/beacon/states/{state_id}/committees
    pub async fn get_epoch_committees(
        &self,
        request: GetEpochCommitteesRequest,
    ) -> anyhow::Result<GetEpochCommitteesResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("beacon")
            .push("states")
            .push(&request.path.state_id.to_string())
            .push("committees");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(GetEpochCommitteesRequest::parse_response(response).await?)
    }
    ///Get state finality checkpoints
    ///
    ///Returns finality checkpoints for state with given 'stateId'.
    ///In case finality is not yet achieved, checkpoint should return epoch 0 and ZERO_HASH as root.
    ///
    ///GET /eth/v1/beacon/states/{state_id}/finality_checkpoints
    pub async fn get_state_finality_checkpoints(
        &self,
        request: GetStateFinalityCheckpointsRequest,
    ) -> anyhow::Result<GetStateFinalityCheckpointsResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("beacon")
            .push("states")
            .push(&request.path.state_id.to_string())
            .push("finality_checkpoints");
        let response = self.client.get(url).send().await?;
        Ok(GetStateFinalityCheckpointsRequest::parse_response(response).await?)
    }
    ///Get Fork object for requested state
    ///
    ///Returns [Fork](https://github.com/ethereum/consensus-specs/blob/v1.3.0/specs/phase0/beacon-chain.md#fork) object for state with given 'stateId'.
    ///
    ///GET /eth/v1/beacon/states/{state_id}/fork
    pub async fn get_state_fork(
        &self,
        request: GetStateForkRequest,
    ) -> anyhow::Result<GetStateForkResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("beacon")
            .push("states")
            .push(&request.path.state_id.to_string())
            .push("fork");
        let response = self.client.get(url).send().await?;
        Ok(GetStateForkRequest::parse_response(response).await?)
    }
    ///Get State Pending Consolidations
    ///
    ///Returns pending consolidations for state with given 'stateId'. Should return 400 if the state retrieved is prior to Electra.
    ///
    ///GET /eth/v1/beacon/states/{state_id}/pending_consolidations
    pub async fn get_pending_consolidations(
        &self,
        request: GetPendingConsolidationsRequest,
    ) -> anyhow::Result<GetPendingConsolidationsResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("beacon")
            .push("states")
            .push(&request.path.state_id.to_string())
            .push("pending_consolidations");
        let response = self.client.get(url).send().await?;
        Ok(GetPendingConsolidationsRequest::parse_response(response).await?)
    }
    ///Get State Pending Deposits
    ///
    ///Returns pending deposits for state with given 'stateId'. Should return 400 if the state retrieved is prior to Electra.
    ///
    ///GET /eth/v1/beacon/states/{state_id}/pending_deposits
    pub async fn get_pending_deposits(
        &self,
        request: GetPendingDepositsRequest,
    ) -> anyhow::Result<GetPendingDepositsResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("beacon")
            .push("states")
            .push(&request.path.state_id.to_string())
            .push("pending_deposits");
        let response = self.client.get(url).send().await?;
        Ok(GetPendingDepositsRequest::parse_response(response).await?)
    }
    ///Get State Pending Partial Withdrawals
    ///
    ///Returns pending partial withdrawals for state with given 'stateId'. Should return 400 if the state retrieved is prior to Electra.
    ///
    ///GET /eth/v1/beacon/states/{state_id}/pending_partial_withdrawals
    pub async fn get_pending_partial_withdrawals(
        &self,
        request: GetPendingPartialWithdrawalsRequest,
    ) -> anyhow::Result<GetPendingPartialWithdrawalsResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("beacon")
            .push("states")
            .push(&request.path.state_id.to_string())
            .push("pending_partial_withdrawals");
        let response = self.client.get(url).send().await?;
        Ok(GetPendingPartialWithdrawalsRequest::parse_response(response).await?)
    }
    ///Get State Proposer Lookahead
    ///
    ///Returns proposer lookahead for state with given 'stateId'. Should return 400 if the state retrieved is prior to Fulu.
    ///
    ///GET /eth/v1/beacon/states/{state_id}/proposer_lookahead
    pub async fn get_proposer_lookahead(
        &self,
        request: GetProposerLookaheadRequest,
    ) -> anyhow::Result<GetProposerLookaheadResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("beacon")
            .push("states")
            .push(&request.path.state_id.to_string())
            .push("proposer_lookahead");
        let response = self.client.get(url).send().await?;
        Ok(GetProposerLookaheadRequest::parse_response(response).await?)
    }
    ///Get the RANDAO mix for some epoch in a specified state.
    ///
    ///Fetch the RANDAO mix for the requested epoch from the state identified by `state_id`.
    ///
    ///If an epoch is not specified then the RANDAO mix for the state's current epoch will be returned.
    ///
    ///By adjusting the `state_id` parameter you can query for any historic value of the RANDAO mix.
    ///Ordinarily states from the same epoch will mutate the RANDAO mix for that epoch as blocks are
    ///applied.
    ///
    ///GET /eth/v1/beacon/states/{state_id}/randao
    pub async fn get_state_randao(
        &self,
        request: GetStateRandaoRequest,
    ) -> anyhow::Result<GetStateRandaoResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("beacon")
            .push("states")
            .push(&request.path.state_id.to_string())
            .push("randao");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(GetStateRandaoRequest::parse_response(response).await?)
    }
    ///Get state SSZ HashTreeRoot
    ///
    ///Calculates HashTreeRoot for state with given 'stateId'. If stateId is root, same value will be returned.
    ///
    ///GET /eth/v1/beacon/states/{state_id}/root
    pub async fn get_state_root(
        &self,
        request: GetStateRootRequest,
    ) -> anyhow::Result<GetStateRootResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("beacon")
            .push("states")
            .push(&request.path.state_id.to_string())
            .push("root");
        let response = self.client.get(url).send().await?;
        Ok(GetStateRootRequest::parse_response(response).await?)
    }
    ///Get sync committees for a state.
    ///
    ///Retrieves the current sync committee for the given state. Also returns the subcommittee assignments.
    ///
    ///GET /eth/v1/beacon/states/{state_id}/sync_committees
    pub async fn get_epoch_sync_committees(
        &self,
        request: GetEpochSyncCommitteesRequest,
    ) -> anyhow::Result<GetEpochSyncCommitteesResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("beacon")
            .push("states")
            .push(&request.path.state_id.to_string())
            .push("sync_committees");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(GetEpochSyncCommitteesRequest::parse_response(response).await?)
    }
    ///Get validator balances from state
    ///
    ///Returns filterable list of validators balances.
    ///
    ///Balances will be returned for all indices or public key that match known validators. If an index or public key does not
    ///match any known validator, no balance will be returned but this will not cause an error. There are no guarantees for the
    ///returned data in terms of ordering; the index is returned for each balance, and can be used to confirm for which inputs a
    ///response has been returned.
    ///
    ///GET /eth/v1/beacon/states/{state_id}/validator_balances
    pub async fn get_state_validator_balances(
        &self,
        request: GetStateValidatorBalancesRequest,
    ) -> anyhow::Result<GetStateValidatorBalancesResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("beacon")
            .push("states")
            .push(&request.path.state_id.to_string())
            .push("validator_balances");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(GetStateValidatorBalancesRequest::parse_response(response).await?)
    }
    ///Get validator balances from state
    ///
    ///Returns filterable list of validators balances.
    ///
    ///Balances will be returned for all indices or public keys that match known validators. If an index or public key does not
    ///match any known validator, no balance will be returned but this will not cause an error. There are no guarantees for the
    ///returned data in terms of ordering; the index is returned for each balance, and can be used to confirm for which inputs a
    ///response has been returned.
    ///
    ///POST /eth/v1/beacon/states/{state_id}/validator_balances
    pub async fn post_state_validator_balances(
        &self,
        request: PostStateValidatorBalancesRequest,
    ) -> anyhow::Result<PostStateValidatorBalancesResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("beacon")
            .push("states")
            .push(&request.path.state_id.to_string())
            .push("validator_balances");
        let mut req_builder = self.client.post(url);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(PostStateValidatorBalancesRequest::parse_response(response).await?)
    }
    ///Get validator identities from state
    ///
    ///Returns filterable list of validators identities.
    ///
    ///Identities will be returned for all indices or public keys that match known validators. If an index or public key does not
    ///match any known validator, no identity will be returned but this will not cause an error. There are no guarantees for the
    ///returned data in terms of ordering.
    ///
    ///Depending on `Accept` header data can be returned either as JSON or as bytes serialized by SSZ.
    ///
    ///POST /eth/v1/beacon/states/{state_id}/validator_identities
    pub async fn post_state_validator_identities(
        &self,
        request: PostStateValidatorIdentitiesRequest,
    ) -> anyhow::Result<PostStateValidatorIdentitiesResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("beacon")
            .push("states")
            .push(&request.path.state_id.to_string())
            .push("validator_identities");
        let mut req_builder = self.client.post(url);
        if let Some(body) = request.body.as_ref() {
            req_builder = req_builder.json(body);
        }
        let response = req_builder.send().await?;
        Ok(PostStateValidatorIdentitiesRequest::parse_response(response).await?)
    }
    ///Get validators from state
    ///
    ///Returns filterable list of validators with their balance, status and index.
    ///
    ///Information will be returned for all indices or public key that match known validators.  If an index or public key does not
    ///match any known validator, no information will be returned but this will not cause an error.  There are no guarantees for the
    ///returned data in terms of ordering; both the index and public key are returned for each validator, and can be used to confirm
    ///for which inputs a response has been returned.
    ///
    ///GET /eth/v1/beacon/states/{state_id}/validators
    pub async fn get_state_validators(
        &self,
        request: GetStateValidatorsRequest,
    ) -> anyhow::Result<GetStateValidatorsResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("beacon")
            .push("states")
            .push(&request.path.state_id.to_string())
            .push("validators");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(GetStateValidatorsRequest::parse_response(response).await?)
    }
    ///Get validators from state
    ///
    ///Returns filterable list of validators with their balance, status and index.
    ///
    ///Information will be returned for all indices or public key that match known validators.  If an index or public key does not
    ///match any known validator, no information will be returned but this will not cause an error.  There are no guarantees for the
    ///returned data in terms of ordering; both the index and public key are returned for each validator, and can be used to confirm
    ///for which inputs a response has been returned.
    ///
    ///The POST variant of this endpoint has the same semantics as the GET endpoint but passes
    ///the lists of IDs and statuses via a POST body in order to enable larger requests.
    ///
    ///POST /eth/v1/beacon/states/{state_id}/validators
    pub async fn post_state_validators(
        &self,
        request: PostStateValidatorsRequest,
    ) -> anyhow::Result<PostStateValidatorsResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("beacon")
            .push("states")
            .push(&request.path.state_id.to_string())
            .push("validators");
        let response = self.client.post(url).json(&request.body).send().await?;
        Ok(PostStateValidatorsRequest::parse_response(response).await?)
    }
    ///Get validator from state by id
    ///
    ///Returns validator specified by state and id or public key along with status and balance.
    ///
    ///GET /eth/v1/beacon/states/{state_id}/validators/{validator_id}
    pub async fn get_state_validator(
        &self,
        request: GetStateValidatorRequest,
    ) -> anyhow::Result<GetStateValidatorResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("beacon")
            .push("states")
            .push(&request.path.state_id.to_string())
            .push("validators")
            .push(&request.path.validator_id.to_string());
        let response = self.client.get(url).send().await?;
        Ok(GetStateValidatorRequest::parse_response(response).await?)
    }
    ///Get deposit contract address.
    ///
    ///Retrieve Eth1 deposit contract address and chain ID.
    ///
    ///GET /eth/v1/config/deposit_contract
    pub async fn get_deposit_contract(
        &self,
        request: GetDepositContractRequest,
    ) -> anyhow::Result<GetDepositContractResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("config")
            .push("deposit_contract");
        let response = self.client.get(url).send().await?;
        Ok(GetDepositContractRequest::parse_response(response).await?)
    }
    ///Get scheduled upcoming forks.
    ///
    ///Retrieve all forks, past present and future, of which this node is aware.
    ///
    ///GET /eth/v1/config/fork_schedule
    pub async fn get_fork_schedule(
        &self,
        request: GetForkScheduleRequest,
    ) -> anyhow::Result<GetForkScheduleResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("config")
            .push("fork_schedule");
        let response = self.client.get(url).send().await?;
        Ok(GetForkScheduleRequest::parse_response(response).await?)
    }
    ///Get spec params.
    ///
    ///Retrieve specification configuration used on this node.  The configuration should include:
    ///- Constants for all hard forks known by the beacon node, for example the [phase 0](https://github.com/ethereum/consensus-specs/blob/v1.3.0/specs/phase0/beacon-chain.md#constants) and [altair](https://github.com/ethereum/consensus-specs/blob/v1.3.0/specs/altair/beacon-chain.md#constants) values
    ///- Presets for all hard forks supplied to the beacon node, for example the [phase 0](https://github.com/ethereum/consensus-specs/blob/v1.3.0/presets/mainnet/phase0.yaml) and [altair](https://github.com/ethereum/consensus-specs/blob/v1.3.0/presets/mainnet/altair.yaml) values
    ///- Configuration for the beacon node, for example the [mainnet](https://github.com/ethereum/consensus-specs/blob/v1.3.0/configs/mainnet.yaml) values
    ///
    ///Values are returned with following format:
    ///- any value starting with 0x in the spec is returned as a hex string
    ///- numeric values are returned as a quoted integer
    ///- array values are returned as a JSON array
    ///
    ///GET /eth/v1/config/spec
    pub async fn get_spec(
        &self,
        request: GetSpecRequest,
    ) -> anyhow::Result<GetSpecResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("config")
            .push("spec");
        let response = self.client.get(url).send().await?;
        Ok(GetSpecRequest::parse_response(response).await?)
    }
    ///Get data column sidecars
    ///
    ///Retrieves data column sidecars for a given block id.
    ///Depending on `Accept` header it can be returned either as json or as bytes serialized by SSZ.
    ///
    ///If the `indices` parameter is specified, only the data column sidecars with the specified indices will be returned. There are no guarantees
    ///for the returned data column sidecars in terms of ordering.
    ///
    ///GET /eth/v1/debug/beacon/data_column_sidecars/{block_id}
    pub async fn get_debug_data_column_sidecars(
        &self,
        request: GetDebugDataColumnSidecarsRequest,
    ) -> anyhow::Result<GetDebugDataColumnSidecarsResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("debug")
            .push("beacon")
            .push("data_column_sidecars")
            .push(&request.path.block_id.to_string());
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(GetDebugDataColumnSidecarsRequest::parse_response(response).await?)
    }
    ///Get fork choice array
    ///
    ///Retrieves all current fork choice context.
    ///
    ///GET /eth/v1/debug/fork_choice
    pub async fn get_debug_fork_choice(
        &self,
        request: GetDebugForkChoiceRequest,
    ) -> anyhow::Result<GetDebugForkChoiceResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("debug")
            .push("fork_choice");
        let response = self.client.get(url).send().await?;
        Ok(GetDebugForkChoiceRequest::parse_response(response).await?)
    }
    ///Subscribe to beacon node events
    ///
    ///Provides endpoint to subscribe to beacon node Server-Sent-Events stream.
    ///Consumers should use [eventsource](https://html.spec.whatwg.org/multipage/server-sent-events.html#the-eventsource-interface)
    ///implementation to listen on those events.
    ///
    ///Servers _may_ send SSE comments beginning with `:` for any purpose, including to keep the
    ///event stream connection alive in the presence of proxy servers.
    ///
    ///GET /eth/v1/events
    pub async fn eventstream(
        &self,
        request: EventstreamRequest,
    ) -> anyhow::Result<EventstreamResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("events");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(EventstreamRequest::parse_response(response).await?)
    }
    ///Get health check
    ///
    ///Returns node health status in http status codes. Useful for load balancers.
    ///
    ///GET /eth/v1/node/health
    pub async fn get_health(
        &self,
        request: GetHealthRequest,
    ) -> anyhow::Result<GetHealthResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("node")
            .push("health");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(GetHealthRequest::parse_response(response).await?)
    }
    ///Get node network identity
    ///
    ///Retrieves data about the node's network presence
    ///
    ///GET /eth/v1/node/identity
    pub async fn get_network_identity(
        &self,
        request: GetNetworkIdentityRequest,
    ) -> anyhow::Result<GetNetworkIdentityResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("node")
            .push("identity");
        let response = self.client.get(url).send().await?;
        Ok(GetNetworkIdentityRequest::parse_response(response).await?)
    }
    ///Get peer count
    ///
    ///Retrieves number of known peers.
    ///
    ///GET /eth/v1/node/peer_count
    pub async fn get_peer_count(
        &self,
        request: GetPeerCountRequest,
    ) -> anyhow::Result<GetPeerCountResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("node")
            .push("peer_count");
        let response = self.client.get(url).send().await?;
        Ok(GetPeerCountRequest::parse_response(response).await?)
    }
    ///Get node network peers
    ///
    ///Retrieves data about the node's network peers. By default this returns all peers. Multiple query params are combined using AND conditions
    ///
    ///GET /eth/v1/node/peers
    pub async fn get_peers(
        &self,
        request: GetPeersRequest,
    ) -> anyhow::Result<GetPeersResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("node")
            .push("peers");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(GetPeersRequest::parse_response(response).await?)
    }
    ///Get peer
    ///
    ///Retrieves data about the given peer
    ///
    ///GET /eth/v1/node/peers/{peer_id}
    pub async fn get_peer(
        &self,
        request: GetPeerRequest,
    ) -> anyhow::Result<GetPeerResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("node")
            .push("peers")
            .push(&request.path.peer_id.to_string());
        let response = self.client.get(url).send().await?;
        Ok(GetPeerRequest::parse_response(response).await?)
    }
    ///Get node syncing status
    ///
    ///Requests the beacon node to describe if it's currently syncing or not, and if it is, what block it is up to.
    ///
    ///GET /eth/v1/node/syncing
    pub async fn get_syncing_status(
        &self,
        request: GetSyncingStatusRequest,
    ) -> anyhow::Result<GetSyncingStatusResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("node")
            .push("syncing");
        let response = self.client.get(url).send().await?;
        Ok(GetSyncingStatusRequest::parse_response(response).await?)
    }
    ///Get version string of the running beacon node.
    ///
    ///Requests that the beacon node identify information about its implementation in a format similar to a  [HTTP User-Agent](https://tools.ietf.org/html/rfc7231#section-5.5.3) field.
    ///
    ///GET /eth/v1/node/version
    pub async fn get_node_version(
        &self,
        request: GetNodeVersionRequest,
    ) -> anyhow::Result<GetNodeVersionResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("node")
            .push("version");
        let response = self.client.get(url).send().await?;
        Ok(GetNodeVersionRequest::parse_response(response).await?)
    }
    ///Produce an attestation data
    ///
    ///Requests that the beacon node produce an AttestationData. For `slot`s in
    ///Electra and later, this AttestationData must have a `committee_index` of 0.
    ///
    ///A 503 error must be returned if the block identified by the response
    ///`beacon_block_root` is optimistic (i.e. the attestation attests to a block
    ///that has not been fully verified by an execution engine).
    ///
    ///GET /eth/v1/validator/attestation_data
    pub async fn produce_attestation_data(
        &self,
        request: ProduceAttestationDataRequest,
    ) -> anyhow::Result<ProduceAttestationDataResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("validator")
            .push("attestation_data");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(ProduceAttestationDataRequest::parse_response(response).await?)
    }
    ///Determine if a distributed validator has been selected to aggregate attestations
    ///
    ///This endpoint should be used by a validator client running as part of a distributed validator cluster, and is
    ///implemented by a distributed validator middleware client. This endpoint is used to exchange partial
    ///selection proofs for combined/aggregated selection proofs to allow a validator client
    ///to correctly determine if any of its validators has been selected to perform an attestation aggregation duty in a slot.
    ///Validator clients running in a distributed validator cluster must query this endpoint at the start of an epoch for the current and lookahead (next) epochs for
    ///all validators that have attester duties in the current and lookahead epochs. Consensus clients need not support this
    ///endpoint and may return a 501.
    ///
    ///POST /eth/v1/validator/beacon_committee_selections
    pub async fn submit_beacon_committee_selections(
        &self,
        request: SubmitBeaconCommitteeSelectionsRequest,
    ) -> anyhow::Result<SubmitBeaconCommitteeSelectionsResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("validator")
            .push("beacon_committee_selections");
        let response = self.client.post(url).json(&request.body).send().await?;
        Ok(SubmitBeaconCommitteeSelectionsRequest::parse_response(response).await?)
    }
    ///Signal beacon node to prepare for a committee subnet
    ///
    ///After beacon node receives this request,
    ///search using discv5 for peers related to this subnet
    ///and replace current peers with those ones if necessary
    ///If validator `is_aggregator`, beacon node must:
    ///- announce subnet topic subscription on gossipsub
    ///- aggregate attestations received on that subnet
    ///
    ///POST /eth/v1/validator/beacon_committee_subscriptions
    pub async fn prepare_beacon_committee_subnet(
        &self,
        request: PrepareBeaconCommitteeSubnetRequest,
    ) -> anyhow::Result<PrepareBeaconCommitteeSubnetResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("validator")
            .push("beacon_committee_subscriptions");
        let response = self.client.post(url).json(&request.body).send().await?;
        Ok(PrepareBeaconCommitteeSubnetRequest::parse_response(response).await?)
    }
    ///Publish multiple contribution and proofs
    ///
    ///Publish multiple signed sync committee contribution and proofs
    ///
    ///POST /eth/v1/validator/contribution_and_proofs
    pub async fn publish_contribution_and_proofs(
        &self,
        request: PublishContributionAndProofsRequest,
    ) -> anyhow::Result<PublishContributionAndProofsResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("validator")
            .push("contribution_and_proofs");
        let response = self.client.post(url).json(&request.body).send().await?;
        Ok(PublishContributionAndProofsRequest::parse_response(response).await?)
    }
    ///Get attester duties
    ///
    ///Requests the beacon node to provide a set of attestation duties, which should be performed by validators, for a particular epoch.
    ///Duties should only need to be checked once per epoch, however a chain reorganization (of > MIN_SEED_LOOKAHEAD epochs) could occur, resulting in a change of duties. For full safety, you should monitor head events and confirm the dependent root in this response matches:
    ///- event.previous_duty_dependent_root when `compute_epoch_at_slot(event.slot) == epoch`
    ///- event.current_duty_dependent_root when `compute_epoch_at_slot(event.slot) + 1 == epoch`
    ///- event.block otherwise
    ///
    ///The dependent_root value is `get_block_root_at_slot(state, compute_start_slot_at_epoch(epoch - 1) - 1)` or the genesis block root in the case of underflow.
    ///
    ///POST /eth/v1/validator/duties/attester/{epoch}
    pub async fn get_attester_duties(
        &self,
        request: GetAttesterDutiesRequest,
    ) -> anyhow::Result<GetAttesterDutiesResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("validator")
            .push("duties")
            .push("attester")
            .push(&request.path.epoch.to_string());
        let response = self.client.post(url).json(&request.body).send().await?;
        Ok(GetAttesterDutiesRequest::parse_response(response).await?)
    }
    ///Get block proposers duties
    ///
    ///Request beacon node to provide all validators that are scheduled to propose a block in the given epoch.
    ///Duties should only need to be checked once per epoch, however a chain reorganization could occur that results in a change of duties. For full safety, you should monitor head events and confirm the dependent root in this response matches:
    ///- event.current_duty_dependent_root when `compute_epoch_at_slot(event.slot) == epoch`
    ///- event.block otherwise
    ///
    ///The dependent_root value is `get_block_root_at_slot(state, compute_start_slot_at_epoch(epoch) - 1)` or the genesis block root in the case of underflow.
    ///
    ///GET /eth/v1/validator/duties/proposer/{epoch}
    pub async fn get_proposer_duties(
        &self,
        request: GetProposerDutiesRequest,
    ) -> anyhow::Result<GetProposerDutiesResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("validator")
            .push("duties")
            .push("proposer")
            .push(&request.path.epoch.to_string());
        let response = self.client.get(url).send().await?;
        Ok(GetProposerDutiesRequest::parse_response(response).await?)
    }
    ///Get sync committee duties
    ///
    ///Requests the beacon node to provide a set of sync committee duties for a particular epoch.
    ///
    ///POST /eth/v1/validator/duties/sync/{epoch}
    pub async fn get_sync_committee_duties(
        &self,
        request: GetSyncCommitteeDutiesRequest,
    ) -> anyhow::Result<GetSyncCommitteeDutiesResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("validator")
            .push("duties")
            .push("sync")
            .push(&request.path.epoch.to_string());
        let response = self.client.post(url).json(&request.body).send().await?;
        Ok(GetSyncCommitteeDutiesRequest::parse_response(response).await?)
    }
    ///Indicates if a validator has been observed on the network
    ///
    ///Requests the beacon node to indicate if a validator has been observed to be live in a given epoch. The beacon node might detect liveness by observing messages from the validator on the network, in the beacon chain, from its API or from any other source. A beacon node SHOULD support the current and previous epoch, however it MAY support earlier epoch. It is important to note that the values returned by the beacon node are not canonical; they are best-effort and based upon a subjective view of the network. A beacon node that was recently started or suffered a network partition may indicate that a validator is not live when it actually is.
    ///
    ///POST /eth/v1/validator/liveness/{epoch}
    pub async fn get_liveness(
        &self,
        request: GetLivenessRequest,
    ) -> anyhow::Result<GetLivenessResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("validator")
            .push("liveness")
            .push(&request.path.epoch.to_string());
        let response = self.client.post(url).json(&request.body).send().await?;
        Ok(GetLivenessRequest::parse_response(response).await?)
    }
    ///Provide beacon node with proposals for the given validators.
    ///
    ///Prepares the beacon node for potential proposers by supplying information
    ///required when proposing blocks for the given validators.  The information
    ///supplied for each validator index will persist through the epoch in which
    ///the call is submitted and for a further two epochs after that, or until the
    ///beacon node restarts.  It is expected that validator clients will send this
    ///information periodically, for example each epoch, to ensure beacon nodes have
    ///correct and timely fee recipient information.
    ///
    ///Note that there is no guarantee that the beacon node will use the supplied fee
    ///recipient when creating a block proposal, so on receipt of a proposed block the
    ///validator should confirm that it finds the fee recipient within the block
    ///acceptable before signing it.
    ///
    ///Also note that requests containing currently inactive or unknown validator
    ///indices will be accepted, as they may become active at a later epoch.
    ///
    ///POST /eth/v1/validator/prepare_beacon_proposer
    pub async fn prepare_beacon_proposer(
        &self,
        request: PrepareBeaconProposerRequest,
    ) -> anyhow::Result<PrepareBeaconProposerResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("validator")
            .push("prepare_beacon_proposer");
        let response = self.client.post(url).json(&request.body).send().await?;
        Ok(PrepareBeaconProposerRequest::parse_response(response).await?)
    }
    ///Provide beacon node with registrations for the given validators to the external builder network.
    ///
    ///Prepares the beacon node for engaging with external builders. The
    ///information must be sent by the beacon node to the builder network. It is
    ///expected that the validator client will send this information periodically
    ///to ensure the beacon node has correct and timely registration information
    ///to provide to builders.
    ///
    ///Note that only registrations for active or pending validators must be sent to the builder network.
    ///Registrations for unknown or exited validators must be filtered out and not sent to the builder network.
    ///
    ///POST /eth/v1/validator/register_validator
    pub async fn register_validator(
        &self,
        request: RegisterValidatorRequest,
    ) -> anyhow::Result<RegisterValidatorResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("validator")
            .push("register_validator");
        let response = self.client.post(url).json(&request.body).send().await?;
        Ok(RegisterValidatorRequest::parse_response(response).await?)
    }
    ///Produce a sync committee contribution
    ///
    ///Requests that the beacon node produce a sync committee contribution.
    ///
    ///A 503 error must be returned if the block identified by the response
    ///`beacon_block_root` is optimistic (i.e. the sync committee contribution
    ///refers to a block that has not been fully verified by an execution engine).
    ///
    ///A 404 error must be returned if no sync committee contribution is available
    ///for the requested `beacon_block_root`.
    ///
    ///GET /eth/v1/validator/sync_committee_contribution
    pub async fn produce_sync_committee_contribution(
        &self,
        request: ProduceSyncCommitteeContributionRequest,
    ) -> anyhow::Result<ProduceSyncCommitteeContributionResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("validator")
            .push("sync_committee_contribution");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(ProduceSyncCommitteeContributionRequest::parse_response(response).await?)
    }
    ///Determine if a distributed validator has been selected to make a sync committee contribution
    ///
    ///Submit sync committee selections to a DVT middleware client. It returns the threshold aggregated sync
    ///committee selection. This endpoint should be used by a validator client running as part of a distributed
    ///validator cluster, and is implemented by a distributed validator middleware client. This endpoint is
    ///used to exchange partial selection proofs (slot signatures) for combined/aggregated selection proofs to
    ///allow a validator client to correctly determine if any of its validators has been selected to perform a
    ///sync committee contribution (sync aggregation) duty in a slot. Validator clients running in a distributed validator cluster must query this endpoint
    ///at the start of each slot for all validators that are included in the current sync committee. Consensus
    ///clients need not support this endpoint and may return a 501.
    ///
    ///POST /eth/v1/validator/sync_committee_selections
    pub async fn submit_sync_committee_selections(
        &self,
        request: SubmitSyncCommitteeSelectionsRequest,
    ) -> anyhow::Result<SubmitSyncCommitteeSelectionsResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("validator")
            .push("sync_committee_selections");
        let response = self.client.post(url).json(&request.body).send().await?;
        Ok(SubmitSyncCommitteeSelectionsRequest::parse_response(response).await?)
    }
    ///Subscribe to sync committee subnets
    ///
    ///Subscribe to a number of sync committee subnets
    ///
    ///Sync committees are not present in phase0, but are required for Altair networks.
    ///
    ///Subscribing to sync committee subnets is an action performed by VC to enable network participation in Altair networks, and only required if the VC has an active validator in an active sync committee.
    ///
    ///POST /eth/v1/validator/sync_committee_subscriptions
    pub async fn prepare_sync_committee_subnets(
        &self,
        request: PrepareSyncCommitteeSubnetsRequest,
    ) -> anyhow::Result<PrepareBeaconProposerResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v1")
            .push("validator")
            .push("sync_committee_subscriptions");
        let response = self.client.post(url).json(&request.body).send().await?;
        Ok(PrepareSyncCommitteeSubnetsRequest::parse_response(response).await?)
    }
    ///Publish a signed block.
    ///
    ///Instructs the beacon node to use the components of the `SignedBlindedBeaconBlock` to construct and publish a
    ///`SignedBeaconBlock` by swapping out the `transactions_root` for the corresponding full list of `transactions`.
    ///The beacon node should broadcast a newly constructed `SignedBeaconBlock` to the beacon network,
    ///to be included in the beacon chain. The beacon node is not required to validate the signed
    ///`BeaconBlock`, and a successful response (20X) only indicates that the broadcast has been
    ///successful. The beacon node is expected to integrate the new block into its state, and
    ///therefore validate the block internally, however blocks which fail the validation are still
    ///broadcast but a different status code is returned (202). Before Bellatrix, this endpoint will accept
    ///a `SignedBeaconBlock`. The broadcast behaviour may be adjusted via the `broadcast_validation`
    ///query parameter.
    ///
    ///POST /eth/v2/beacon/blinded_blocks
    pub async fn publish_blinded_block_v2(
        &self,
        request: PublishBlindedBlockV2Request,
    ) -> anyhow::Result<PublishBlockV2Response> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v2")
            .push("beacon")
            .push("blinded_blocks");
        let response = self
            .client
            .post(url)
            .query(&request.query)
            .headers(
                http::HeaderMap::try_from(&request.header)
                    .context("building request headers")?,
            )
            .json(&request.body)
            .send()
            .await?;
        Ok(PublishBlindedBlockV2Request::parse_response(response).await?)
    }
    ///Publish a signed block.
    ///
    ///Instructs the beacon node to broadcast a newly signed beacon block to the beacon network,
    ///to be included in the beacon chain. A success response (20x) indicates that the block
    ///passed gossip validation and was successfully broadcast onto the network.
    ///The beacon node is also expected to integrate the block into the state, but may broadcast it
    ///before doing so, so as to aid timely delivery of the block. Should the block fail full
    ///validation, a separate success response code (202) is used to indicate that the block was
    ///successfully broadcast but failed integration. After Deneb, this additionally instructs
    ///the beacon node to broadcast all given blobs. The broadcast behaviour may be adjusted via the
    ///`broadcast_validation` query parameter.
    ///
    ///POST /eth/v2/beacon/blocks
    pub async fn publish_block_v2(
        &self,
        request: PublishBlockV2Request,
    ) -> anyhow::Result<PublishBlockV2Response> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v2")
            .push("beacon")
            .push("blocks");
        let response = self
            .client
            .post(url)
            .query(&request.query)
            .headers(
                http::HeaderMap::try_from(&request.header)
                    .context("building request headers")?,
            )
            .json(&request.body)
            .send()
            .await?;
        Ok(PublishBlockV2Request::parse_response(response).await?)
    }
    ///Get block
    ///
    ///Retrieves block details for given block id.
    ///Depending on `Accept` header it can be returned either as json or as bytes serialized by SSZ
    ///
    ///GET /eth/v2/beacon/blocks/{block_id}
    pub async fn get_block_v2(
        &self,
        request: GetBlockV2Request,
    ) -> anyhow::Result<GetBlockV2Response> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v2")
            .push("beacon")
            .push("blocks")
            .push(&request.path.block_id.to_string());
        let response = self.client.get(url).send().await?;
        Ok(GetBlockV2Request::parse_response(response).await?)
    }
    ///Get block attestations
    ///
    ///Retrieves attestation included in requested block.
    ///
    ///GET /eth/v2/beacon/blocks/{block_id}/attestations
    pub async fn get_block_attestations_v2(
        &self,
        request: GetBlockAttestationsV2Request,
    ) -> anyhow::Result<GetBlockAttestationsV2Response> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v2")
            .push("beacon")
            .push("blocks")
            .push(&request.path.block_id.to_string())
            .push("attestations");
        let response = self.client.get(url).send().await?;
        Ok(GetBlockAttestationsV2Request::parse_response(response).await?)
    }
    ///Get attestations from operations pool
    ///
    ///Retrieves attestations known by the node but not necessarily incorporated into any block
    ///
    ///GET /eth/v2/beacon/pool/attestations
    pub async fn get_pool_attestations_v2(
        &self,
        request: GetPoolAttestationsV2Request,
    ) -> anyhow::Result<GetPoolAttestationsV2Response> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v2")
            .push("beacon")
            .push("pool")
            .push("attestations");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(GetPoolAttestationsV2Request::parse_response(response).await?)
    }
    ///Submit Attestation objects to node
    ///
    ///Submits attestations to the node. Each attestation in the request body is processed individually.
    ///
    ///If an attestation is validated successfully, the node MUST publish that attestation on the appropriate subnet.
    ///
    ///If one or more attestations fail validation, the node MUST return a 400 error with details of which attestations have failed, and why.
    ///
    ///Prior to the Electra hard fork, this endpoint MUST be sent Attestation objects only.  At and after the Electra hard fork, this endpoint MUST be sent SingleAttestation objects only.
    ///
    ///POST /eth/v2/beacon/pool/attestations
    pub async fn submit_pool_attestations_v2(
        &self,
        request: SubmitPoolAttestationsV2Request,
    ) -> anyhow::Result<SubmitPoolAttestationsV2Response> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v2")
            .push("beacon")
            .push("pool")
            .push("attestations");
        let response = self
            .client
            .post(url)
            .headers(
                http::HeaderMap::try_from(&request.header)
                    .context("building request headers")?,
            )
            .json(&request.body)
            .send()
            .await?;
        Ok(SubmitPoolAttestationsV2Request::parse_response(response).await?)
    }
    ///Get attester slashings from operations pool
    ///
    ///Retrieves attester slashings known by the node but not necessarily incorporated into any block
    ///
    ///GET /eth/v2/beacon/pool/attester_slashings
    pub async fn get_pool_attester_slashings_v2(
        &self,
        request: GetPoolAttesterSlashingsV2Request,
    ) -> anyhow::Result<GetPoolAttesterSlashingsV2Response> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v2")
            .push("beacon")
            .push("pool")
            .push("attester_slashings");
        let response = self.client.get(url).send().await?;
        Ok(GetPoolAttesterSlashingsV2Request::parse_response(response).await?)
    }
    ///Submit AttesterSlashing object to node's pool
    ///
    ///Submits AttesterSlashing object to node's pool. Upon successful validation the node MUST broadcast it to network.
    ///
    ///POST /eth/v2/beacon/pool/attester_slashings
    pub async fn submit_pool_attester_slashings_v2(
        &self,
        request: SubmitPoolAttesterSlashingsV2Request,
    ) -> anyhow::Result<SubmitPoolVoluntaryExitResponse> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v2")
            .push("beacon")
            .push("pool")
            .push("attester_slashings");
        let response = self
            .client
            .post(url)
            .headers(
                http::HeaderMap::try_from(&request.header)
                    .context("building request headers")?,
            )
            .json(&request.body)
            .send()
            .await?;
        Ok(SubmitPoolAttesterSlashingsV2Request::parse_response(response).await?)
    }
    ///Get fork choice leaves
    ///
    ///Retrieves all possible chain heads (leaves of fork choice tree).
    ///
    ///GET /eth/v2/debug/beacon/heads
    pub async fn get_debug_chain_heads_v2(
        &self,
        request: GetDebugChainHeadsV2Request,
    ) -> anyhow::Result<GetDebugChainHeadsV2Response> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v2")
            .push("debug")
            .push("beacon")
            .push("heads");
        let response = self.client.get(url).send().await?;
        Ok(GetDebugChainHeadsV2Request::parse_response(response).await?)
    }
    ///Get full BeaconState object
    ///
    ///Returns full BeaconState object for given stateId.
    ///Depending on `Accept` header it can be returned either as json or as bytes serialized by SSZ
    ///
    ///GET /eth/v2/debug/beacon/states/{state_id}
    pub async fn get_state_v2(
        &self,
        request: GetStateV2Request,
    ) -> anyhow::Result<GetStateV2Response> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v2")
            .push("debug")
            .push("beacon")
            .push("states")
            .push(&request.path.state_id.to_string());
        let response = self.client.get(url).send().await?;
        Ok(GetStateV2Request::parse_response(response).await?)
    }
    ///Publish multiple aggregate and proofs
    ///
    ///Verifies given aggregate and proofs and publishes them on appropriate gossipsub topic.
    ///
    ///POST /eth/v2/validator/aggregate_and_proofs
    pub async fn publish_aggregate_and_proofs_v2(
        &self,
        request: PublishAggregateAndProofsV2Request,
    ) -> anyhow::Result<SubmitPoolAttestationsV2Response> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v2")
            .push("validator")
            .push("aggregate_and_proofs");
        let response = self
            .client
            .post(url)
            .headers(
                http::HeaderMap::try_from(&request.header)
                    .context("building request headers")?,
            )
            .json(&request.body)
            .send()
            .await?;
        Ok(PublishAggregateAndProofsV2Request::parse_response(response).await?)
    }
    ///Get aggregated attestation
    ///
    ///Aggregates all attestations matching given attestation data root, slot and committee index.
    ///
    ///A 503 error must be returned if the block identified by the response
    ///`beacon_block_root` is optimistic (i.e. the aggregated attestation attests
    ///to a block that has not been fully verified by an execution engine).
    ///
    ///A 404 error must be returned if no attestation is available for the requested
    ///`attestation_data_root`.
    ///
    ///GET /eth/v2/validator/aggregate_attestation
    pub async fn get_aggregated_attestation_v2(
        &self,
        request: GetAggregatedAttestationV2Request,
    ) -> anyhow::Result<GetAggregatedAttestationV2Response> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v2")
            .push("validator")
            .push("aggregate_attestation");
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(GetAggregatedAttestationV2Request::parse_response(response).await?)
    }
    ///Produce a new block, without signature.
    ///
    ///Requests a beacon node to produce a valid block, which can then be signed by a validator. The
    ///returned block may be blinded or unblinded, depending on the current state of the network as
    ///decided by the execution and beacon nodes.
    ///
    ///The beacon node must return an unblinded block if it obtains the execution payload from its
    ///paired execution node. It must only return a blinded block if it obtains the execution payload
    ///header from an MEV relay.
    ///
    ///Metadata in the response indicates the type of block produced, and the supported types of block
    ///will be added to as forks progress.
    ///
    ///GET /eth/v3/validator/blocks/{slot}
    pub async fn produce_block_v3(
        &self,
        request: ProduceBlockV3Request,
    ) -> anyhow::Result<ProduceBlockV3Response> {
        request.validate().context("parameter validation")?;
        let mut url = self.base_url.clone();
        url.path_segments_mut()
            .map_err(|()| anyhow::anyhow!("URL cannot be a base"))?
            .push("eth")
            .push("v3")
            .push("validator")
            .push("blocks")
            .push(&request.path.slot.to_string());
        let response = self.client.get(url).query(&request.query).send().await?;
        Ok(ProduceBlockV3Request::parse_response(response).await?)
    }
}

