//! # Charon Core Build Script
//!
//! This build script compiles the protobuf files.

use std::{fs, io::Result, path::PathBuf, process::Command};

fn main() -> Result<()> {
    let proto_dir = "src/corepb/v1";

    let proto_files: Vec<PathBuf> = fs::read_dir(proto_dir)?
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.path())
        .filter(|path| path.extension().is_some_and(|ext| ext == "proto"))
        .collect();

    if proto_files.is_empty() {
        println!("cargo:warning=No .proto files found in {}", proto_dir);
        return Ok(());
    }

    let mut config = prost_build::Config::new();
    config.btree_map(["."]).bytes(["."]).out_dir(proto_dir);

    config.compile_protos(
        &proto_files.iter().map(|p| p.as_path()).collect::<Vec<_>>(),
        &[proto_dir],
    )?;

    add_file_attributes(proto_dir)?;
    format_generated_files(proto_dir)?;

    for proto_file in &proto_files {
        println!("cargo:rerun-if-changed={}", proto_file.display());
    }
    println!("cargo:rerun-if-changed={}", proto_dir);
    println!("cargo:rerun-if-changed=build.rs");

    Ok(())
}

fn add_file_attributes(proto_dir: &str) -> Result<()> {
    let header = "// This file is @generated by prost-build.\n\
    #![allow(dead_code)]\n\
    #![allow(missing_docs)]\n\
    #![allow(clippy::all)]\n\
    #![allow(rustdoc::all)]\n\n";

    let generated_files: Vec<PathBuf> = fs::read_dir(proto_dir)?
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.path())
        .filter(|path| {
            path.extension().is_some_and(|ext| ext == "rs")
                && path.file_name().is_some_and(|name| name != "mod.rs")
        })
        .collect();

    for file_path in generated_files {
        let content = fs::read_to_string(&file_path)?;
        let mut lines = content.lines();
        let first_line = lines.next();
        let rest: String = if let Some(line) = first_line {
            if line.trim() == "// This file is @generated by prost-build." {
                lines.collect::<Vec<_>>().join("\n")
            } else {
                std::iter::once(line)
                    .chain(lines)
                    .collect::<Vec<_>>()
                    .join("\n")
            }
        } else {
            String::new()
        };
        let new_content = format!("{}{}", header, rest);
        fs::write(&file_path, new_content)?;
    }

    Ok(())
}

fn format_generated_files(proto_dir: &str) -> Result<()> {
    let output = Command::new("cargo")
        .args(["+nightly", "fmt", "--", proto_dir])
        .output()
        .or_else(|_| {
            println!("cargo:warning=Nightly rustfmt not available, using stable");
            Command::new("cargo")
                .args(["fmt", "--", proto_dir])
                .output()
        })?;

    if !output.status.success() {
        println!(
            "cargo:warning=Failed to format generated files: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }

    Ok(())
}
