//! Partial signature exchange codec helpers used by core types.
//!
//! Wire format (Charon-compatible): SSZ binary for SSZ-capable types, JSON for
//! everything else; on decode, a leading `{` flips the path to JSON. The
//! per-type codec choice and the duty-keyed decoder dispatch table both come
//! from the `register_signed_data_codecs!` invocation in `signeddata.rs` —
//! this module is just the thin glue.

use crate::{
    marshal::MarshalError,
    signeddata, ssz_codec,
    types::{DutyType, SignedData},
};

/// Error type for partial signature exchange codec operations.
#[derive(Debug, thiserror::Error)]
pub enum ParSigExCodecError {
    /// Missing duty or data set fields.
    #[error("invalid parsigex msg fields")]
    InvalidMessageFields,

    /// Invalid partial signed data set proto.
    #[error("invalid partial signed data set proto fields")]
    InvalidParSignedDataSetFields,

    /// Invalid partial signed proto.
    #[error("invalid partial signed proto")]
    InvalidParSignedProto,

    /// Invalid duty type.
    #[error("invalid duty")]
    InvalidDuty,

    /// Unsupported duty type.
    #[error("unsupported duty type")]
    UnsupportedDutyType,

    /// Deprecated builder proposer duty.
    #[error("deprecated duty builder proposer")]
    DeprecatedBuilderProposer,

    /// Failed to parse a public key.
    #[error("invalid public key: {0}")]
    InvalidPubKey(String),

    /// Invalid share index.
    #[error("invalid share index")]
    InvalidShareIndex,

    /// JSON serialization failed.
    #[error("marshal signed data: {0}")]
    Serialize(#[from] serde_json::Error),

    /// SSZ codec error.
    #[error("ssz codec: {0}")]
    SszCodec(#[from] ssz_codec::SszCodecError),

    /// Signed data construction error.
    #[error("signed data: {0}")]
    SignedData(String),

    /// Failed to extract the signature from signed data.
    #[error("invalid signature: {0}")]
    InvalidSignature(String),
}

impl From<MarshalError> for ParSigExCodecError {
    fn from(err: MarshalError) -> Self {
        match err {
            MarshalError::Json(e) => ParSigExCodecError::Serialize(e),
            MarshalError::Ssz(msg) => {
                ParSigExCodecError::SszCodec(ssz_codec::SszCodecError::Decode(msg))
            }
            MarshalError::Custom(msg) => ParSigExCodecError::SignedData(msg),
            MarshalError::AllFailed => ParSigExCodecError::UnsupportedDutyType,
        }
    }
}

pub(crate) fn serialize_signed_data(data: &dyn SignedData) -> Result<Vec<u8>, ParSigExCodecError> {
    data.marshal().map_err(ParSigExCodecError::from)
}

pub(crate) fn deserialize_signed_data(
    duty_type: &DutyType,
    bytes: &[u8],
) -> Result<Box<dyn SignedData>, ParSigExCodecError> {
    // Duties that never reach the dispatch table.
    match duty_type {
        DutyType::BuilderProposer => return Err(ParSigExCodecError::DeprecatedBuilderProposer),
        DutyType::Unknown | DutyType::InfoSync | DutyType::DutySentinel(_) => {
            return Err(ParSigExCodecError::UnsupportedDutyType);
        }
        _ => {}
    }

    // Walk the table in declared priority order. A decoder failing to parse
    // its prioritized format is not fatal — JSON-only payloads at one
    // priority and SSZ payloads at another can both legitimately appear for
    // duties with multiple registered entries (e.g. `Attester` =
    // `Attestation` then `VersionedAttestation`).
    let mut last_err: Option<MarshalError> = None;
    for (entry_duty, _priority, decoder) in signeddata::dispatch_table() {
        if entry_duty != duty_type {
            continue;
        }
        match decoder(bytes) {
            Ok(value) => return Ok(value),
            Err(e) => last_err = Some(e),
        }
    }

    Err(last_err
        .map(ParSigExCodecError::from)
        .unwrap_or(ParSigExCodecError::UnsupportedDutyType))
}

#[cfg(test)]
mod tests {
    //! Round-trip / duty-dispatch tests for the registered `SignedData` types
    //! are auto-generated by `register_signed_data_codecs!` in
    //! `signeddata.rs`. Tests here cover only behavior specific to this thin
    //! wrapper — duties handled outside the dispatch table and the JSON
    //! fallback that crosses priority boundaries.

    use super::*;
    use crate::signeddata::{Attestation, VersionedAttestation};
    use pluto_eth2api::{spec::phase0, versioned};
    use pluto_ssz::BitList;

    fn sample_attestation_data() -> phase0::AttestationData {
        phase0::AttestationData {
            slot: 42,
            index: 7,
            beacon_block_root: [0xaa; 32],
            source: phase0::Checkpoint {
                epoch: 10,
                root: [0xbb; 32],
            },
            target: phase0::Checkpoint {
                epoch: 11,
                root: [0xcc; 32],
            },
        }
    }

    /// Helper: downcast a `Box<dyn SignedData>` to a concrete type.
    fn downcast<T: SignedData + 'static>(boxed: Box<dyn SignedData>) -> T {
        let any = boxed as Box<dyn std::any::Any>;
        *any.downcast::<T>().expect("type mismatch in downcast")
    }

    #[test]
    fn deprecated_builder_proposer_returns_specific_error() {
        let err = deserialize_signed_data(&DutyType::BuilderProposer, b"any").unwrap_err();
        assert!(matches!(err, ParSigExCodecError::DeprecatedBuilderProposer));
    }

    #[test]
    fn unknown_duty_unsupported() {
        for duty in [DutyType::Unknown, DutyType::InfoSync] {
            let err = deserialize_signed_data(&duty, b"{}").unwrap_err();
            assert!(matches!(err, ParSigExCodecError::UnsupportedDutyType));
        }
    }

    /// JSON at priority 1 still decodes when priority 0's JSON form fails —
    /// an Attester payload that is JSON-encoded `VersionedAttestation` should
    /// not be rejected by `Attestation`'s schema mismatch.
    #[test]
    fn json_falls_through_priorities() {
        let inner = versioned::VersionedAttestation {
            version: versioned::DataVersion::Deneb,
            validator_index: None,
            attestation: Some(versioned::AttestationPayload::Deneb(phase0::Attestation {
                aggregation_bits: BitList::with_bits(16, &[1, 3]),
                data: sample_attestation_data(),
                signature: [0x22; 96],
            })),
        };
        let va = VersionedAttestation::new(inner).unwrap();
        let json_bytes = serde_json::to_vec(&va).unwrap();
        assert_eq!(json_bytes.first(), Some(&b'{'));
        // priority 0 (`Attestation`) cannot decode this JSON; priority 1
        // (`VersionedAttestation`) can.
        let decoded: VersionedAttestation =
            downcast(deserialize_signed_data(&DutyType::Attester, &json_bytes).unwrap());
        assert_eq!(va, decoded);
    }

    /// SSZ at priority 1 still decodes when priority 0's SSZ form fails.
    #[test]
    fn ssz_falls_through_priorities() {
        let att = Attestation::new(phase0::Attestation {
            aggregation_bits: BitList::with_bits(8, &[0, 2]),
            data: sample_attestation_data(),
            signature: [0x11; 96],
        });
        let bytes = serialize_signed_data(&att).unwrap();
        assert_ne!(bytes.first(), Some(&b'{'));
        let decoded: Attestation =
            downcast(deserialize_signed_data(&DutyType::Attester, &bytes).unwrap());
        assert_eq!(att, decoded);
    }
}
