//! Test utilities for the Charon core.

use rand::{Rng, SeedableRng};

use crate::types::PubKey;

/// The size of a BLS public key in bytes.
const PK_LEN: usize = 48;

/// Creates a new seeded random number generator.
///
/// Returns a new random number generator seeded with a random value.
/// This matches the Go implementation: `rand.New(rand.NewSource(rand.Int63()))`.
pub fn new_seed_rand() -> impl Rng {
    let seed = rand::random::<u64>();
    rand::rngs::StdRng::seed_from_u64(seed)
}

/// Returns a random core workflow pubkey.
///
/// This is a convenience wrapper around `random_core_pub_key_seed` that creates
/// a new random seed for each call.
pub fn random_core_pub_key() -> PubKey {
    random_core_pub_key_seed(new_seed_rand())
}

/// Returns a random core workflow pubkey using a provided random source.
///
/// # Arguments
///
/// * `rng` - A random number generator to use for generating the pubkey.
///
/// # Panics
///
/// Panics if the generated bytes cannot be converted to a valid PubKey.
/// This should never happen in practice as we generate exactly 48 bytes.
pub fn random_core_pub_key_seed<R: Rng>(mut rng: R) -> PubKey {
    let pubkey = deterministic_pub_key_seed(&mut rng);
    PubKey::try_from(&pubkey[..]).expect("valid pubkey length")
}

/// Generates a deterministic pubkey from a seeded RNG.
///
/// This function creates a new RNG seeded from the input RNG, then fills
/// a 48-byte array with random data. This matches the Go implementation:
///
/// ```go
/// random := rand.New(rand.NewSource(r.Int63()))
/// var key tbls.PublicKey
/// _, err := random.Read(key[:])
/// ```
///
/// # Arguments
///
/// * `rng` - A mutable reference to a random number generator.
///
/// # Returns
///
/// A 48-byte array containing random data suitable for use as a public key.
fn deterministic_pub_key_seed<R: Rng>(rng: &mut R) -> [u8; PK_LEN] {
    // Create a new RNG seeded from the input RNG (matching Go's rand.New(rand.NewSource(r.Int63())))
    let seed: u64 = rng.r#gen();
    let mut seeded_rng = rand::rngs::StdRng::seed_from_u64(seed);

    let mut key = [0u8; PK_LEN];
    // Fill the key with random bytes
    for byte in &mut key {
        *byte = seeded_rng.r#gen();
    }

    key
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_new_seed_rand_produces_different_values() {
        let mut rng1 = new_seed_rand();
        let mut rng2 = new_seed_rand();

        let val1: u64 = rng1.r#gen();
        let val2: u64 = rng2.r#gen();

        // These should be different with very high probability
        assert_ne!(val1, val2);
    }

    #[test]
    fn test_random_core_pub_key_generates_valid_keys() {
        let pk1 = random_core_pub_key();
        let pk2 = random_core_pub_key();

        // Keys should be different
        assert_ne!(pk1, pk2);

        // Keys should have the correct length when serialized
        assert_eq!(pk1.to_string().len(), 98); // 0x + 96 hex chars
        assert_eq!(pk2.to_string().len(), 98);
    }

    #[test]
    fn test_random_core_pub_key_seed_is_deterministic() {
        let seed = 12345u64;
        let mut rng1 = rand::rngs::StdRng::seed_from_u64(seed);
        let mut rng2 = rand::rngs::StdRng::seed_from_u64(seed);

        let pk1 = random_core_pub_key_seed(&mut rng1);
        let pk2 = random_core_pub_key_seed(&mut rng2);

        // Same seed should produce same key
        assert_eq!(pk1, pk2);
    }

    #[test]
    fn test_deterministic_pub_key_seed() {
        let seed = 42u64;
        let mut rng = rand::rngs::StdRng::seed_from_u64(seed);

        let key = deterministic_pub_key_seed(&mut rng);

        // Check that we got 48 bytes
        assert_eq!(key.len(), PK_LEN);

        // Check that the key is not all zeros (very unlikely with a proper RNG)
        assert!(key.iter().any(|&b| b != 0));
    }

    #[test]
    fn test_random_core_pub_key_seed_different_rngs() {
        let mut rng1 = rand::rngs::StdRng::seed_from_u64(1);
        let mut rng2 = rand::rngs::StdRng::seed_from_u64(2);

        let pk1 = random_core_pub_key_seed(&mut rng1);
        let pk2 = random_core_pub_key_seed(&mut rng2);

        // Different seeds should produce different keys
        assert_ne!(pk1, pk2);
    }
}
