name: Update code coverage

on:
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings -C debuginfo=0"

jobs:
  coverage:
    timeout-minutes: 20
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Cache cargo registry and target
        uses: Swatinem/rust-cache@v2

      - name: Install `protobuf`
        uses: awalsh128/cache-apt-pkgs-action@v1.6.0
        with:
          packages: protobuf-compiler
          version: 3.21.12-8.2ubuntu0.2

      - name: Install `oas3-gen`
        run: cargo install oas3-gen@0.24.0

      - name: Install `llvm-tools-preview`
        run: rustup component add llvm-tools-preview

      - name: Install `cargo-llvm-cov`
        run: cargo install cargo-llvm-cov@0.6.24

      - name: Checkout the wiki repository
        uses: actions/checkout@v2
        with:
          repository: "${{ github.repository }}.wiki"
          # As of Jul 2021, the default branch of a GitHub wiki is `master`, not `main`
          ref: master
          path: .wiki

      - uses: actions/setup-node@v2
      - name: Generate the Coverage Badge
        run: curl -sSL 'https://img.shields.io/badge/coverage-50%25-blue' -o coverage.svg

      - name: Configure the GitHub wiki identity
        working-directory: .wiki
        run: |
          git config user.name  "[bot] ${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Update the wiki page
        working-directory: .wiki
        run: |
          git add .
          git commit --allow-empty -m "Update coverage badge (${GITHUB_WORKFLOW})"
          git push origin master

      # - name: Generate coverage report
      #   run: cargo llvm-cov --workspace --lcov --output-path lcov.info --ignore-filename-regex '^examples/'

      # - name: Upload branch coverage artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: coverage-lcov
      #     path: lcov.info
      #     retention-days: 21

