name: PR Naming Convention
on:
  pull_request:
    types: [edited, opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  title-check:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: Validate PR
        run: |
          pr_name="${{ github.event.pull_request.title }}"
          if [[ ! "$pr_name" =~ ^(fix|feat|build|chore|docs|test|refactor|ci|localize|bump|revert)(\([a-z0-9\-]+\))?:\ .+$ ]]; then
            echo "Error: PR title does not follow the convention: '$pr_name'"
            echo "Expected format: <type>[(scope)]: <description>"
            echo "Where:"
            echo "  <type> is one of fix, feat, build, chore, docs, test, refactor, ci, localize, bump or revert"
            echo "  <scope> is a an optional lowercase string with hyphens or numbers"
            echo "  <description> is a brief summary of the change"
            exit 1
          fi
        shell: bash
