name: Publish Dockerhub

on:
  workflow_dispatch:
  push:
    tags: ["v*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  metadata:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    outputs:
      git_commit_hash_short: ${{ steps.set_outputs.outputs.git_commit_hash_short }}
      source_date_epoch: ${{ steps.set_outputs.outputs.source_date_epoch }}
    steps:
      - uses: actions/checkout@v4

      - name: Set outputs
        id: set_outputs
        run: |
          echo "git_commit_hash_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "source_date_epoch=$(git log -1 --format=%ct)" >> $GITHUB_OUTPUT

  push-to-dockerhub:
    uses: NethermindEth/github-workflows/.github/workflows/docker-build-push-dockerhub.yaml@main
    needs: metadata
    with:
      image_name: "pluto"
      additional_tags: ${{ github.ref_type == 'tag' && github.ref_name || needs.metadata.outputs.git_commit_hash_short }}
      platforms: linux/amd64
      docker_build_args: |
        GIT_COMMIT_HASH_SHORT=${{ needs.metadata.outputs.git_commit_hash_short }}
        SOURCE_DATE_EPOCH=${{ needs.metadata.outputs.source_date_epoch }}
    secrets:
      dockerhub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      dockerhub_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
